// Writes config/laya/requirements.lock from config/laya/requirements.in (docs/laya-auto.md 7.2):
//
//   node scripts/laya-lock.mjs [--check] [--uv <path to uv>]
//
// One universal, hash-pinned lock for every platform: the laptop installs it, and so does the cloud
// end-to-end test, so the file the laptop gets has been installed before it gets it. Torch is left
// out (--no-emit-package torch): its CUDA wheel comes from whichever PyTorch index the driver
// allows, and step 4 of the install puts it in first. Every other dependency is pinned with its
// hashes, transformers and huggingface_hub included, because Laya ships releases by the day.
//
// Reproducible: resolved from PyPI only (any index the environment names is dropped), with the uv
// version config/laya.json pins (a different uv is refused rather than trusted to resolve the same),
// and bounded by the `# exclude-newer:` line of requirements.in, so running it again gives the same
// file until that line is moved on purpose. --check compiles to a temporary file and exits 1 when it
// differs from the committed lock, 0 when it matches.
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const IN = 'config/laya/requirements.in'
const LOCK = 'config/laya/requirements.lock'
const fail = (why) => { console.error(`laya-lock: ${why}`); process.exit(2) }

const args = process.argv.slice(2)
let check = false
let uvGiven = null
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--check') check = true
  else if (args[i] === '--uv') uvGiven = args[++i] ?? fail('--uv needs a path')
  else fail(`unknown argument ${args[i]}; usage: node scripts/laya-lock.mjs [--check] [--uv <path>]`)
}

const pins = JSON.parse(readFileSync(join(root, 'config', 'laya.json'), 'utf8'))
const input = readFileSync(join(root, IN), 'utf8')
const cutoff = /^#\s*exclude-newer:\s*(\S+)\s*$/m.exec(input)?.[1] ?? fail(`${IN} has no "# exclude-newer: <UTC time>" line`)
if (Number.isNaN(Date.parse(cutoff))) fail(`${IN}: exclude-newer ${cutoff} is not a time`)
// The two files name the same versions, or the install would check for one and lock the other.
const pinned = (name) => new RegExp(`^${name}(\\[[^\\]]*\\])?==(\\S+)\\s*$`, 'm').exec(input)?.[2]
if (pinned('laya') !== pins.laya) fail(`${IN} pins laya ${pinned('laya')}, config/laya.json ${pins.laya}`)
if (pinned('torch') !== pins.torch.version) fail(`${IN} pins torch ${pinned('torch')}, config/laya.json ${pins.torch.version}`)

// uv: as given, else the harness's own (engine/uv), else the one on PATH; it must be the pinned one.
const exe = process.platform === 'win32' ? 'uv.exe' : 'uv'
const uv = uvGiven ?? process.env.UV ?? (existsSync(join(root, 'engine', 'uv', exe)) ? join(root, 'engine', 'uv', exe) : 'uv')
let version = ''
try { version = execFileSync(uv, ['--version'], { encoding: 'utf8' }).trim() } catch { fail(`no uv at ${uv}; pass --uv <path to uv ${pins.uv.version}>`) }
if (!version.startsWith(`uv ${pins.uv.version}`)) fail(`${uv} is ${version}; the lock is made with uv ${pins.uv.version} (config/laya.json). Pass --uv <path to uv ${pins.uv.version}>.`)

// PyPI and nothing else: an index, extra index or cutoff set in the environment would change the
// result on one machine only. The cache is a fresh folder, deleted afterwards.
const env = { ...process.env, UV_NO_CONFIG: '1' }
for (const k of Object.keys(env)) if (/^(UV_(INDEX|EXTRA_INDEX|DEFAULT_INDEX|FIND_LINKS|EXCLUDE_NEWER)|PIP_(INDEX|EXTRA_INDEX|FIND_LINKS))/i.test(k)) delete env[k]
const scratch = mkdtempSync(join(tmpdir(), 'laya-lock-'))
env.UV_CACHE_DIR = join(scratch, 'cache')
const out = check ? join(scratch, 'requirements.lock') : join(root, LOCK)
const compile = [
  'pip', 'compile', IN,
  '--universal', '--python-version', pins.python, '--generate-hashes', '--no-emit-package', 'torch',
  '--exclude-newer', cutoff, '--default-index', 'https://pypi.org/simple',
  '--custom-compile-command', 'node scripts/laya-lock.mjs',
  '--quiet', '-o', out,
]
try {
  const r = spawnSync(uv, compile, { cwd: root, env, encoding: 'utf8' })
  if (r.status !== 0) fail(`uv pip compile failed:\n${(r.stderr || r.stdout || '').trim()}`)
  // Which uv made it and from what, under uv's own header, so the file says how to make it again.
  const made = readFileSync(out, 'utf8').replace(
    /^(# This file was autogenerated by uv via the following command:\n#\s+node scripts\/laya-lock\.mjs\n)/,
    `$1#    (${version.split(' (')[0]}, from PyPI as it was at ${cutoff}, universal, hashes, torch left out)\n`,
  )
  if (check) {
    const committed = existsSync(join(root, LOCK)) ? readFileSync(join(root, LOCK), 'utf8') : ''
    if (committed !== made) { console.error(`laya-lock: ${LOCK} differs from a fresh compile; run node scripts/laya-lock.mjs`); process.exitCode = 1 }
    else console.log(`laya-lock: ${LOCK} matches a fresh compile (${version.split(' (')[0]}).`)
  } else {
    writeFileSync(out, made)
    const n = (made.match(/^[a-z0-9][\w.-]*==/gim) ?? []).length
    console.log(`laya-lock: wrote ${LOCK}, ${n} packages pinned with hashes (${version.split(' (')[0]}, PyPI as at ${cutoff}).`)
  }
} finally {
  rmSync(scratch, { recursive: true, force: true })
}
